on:
  push:
    branches:
      - main

jobs:
  block-sensitive-data-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Sensitive Data
        uses: reviewdog/action-git-secrets@v2.x
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Customize scan options as needed
          scan_key: aws_access_key_id|aws_secret_access_key|password|private_key

      - name: Block Commit if Sensitive Data Found
        uses: sdras/lock-threads-on-label-action@v4
        if: always()
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          label-name: 'Sensitive Data Found'
          custom-message: 'Commit blocked: sensitive data detected in changes'

      - name: Auto-commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Block commit: sensitive data detected in changes'
          commit_options: '--no-verify'
